# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'users-backend-api'
primary_region = 'gru'  # SÃ£o Paulo

[build]

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Uncomment after volume is created:
# [[mounts]]
#   source = 'users_db_data'
#   destination = '/app/data'
